/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Principal;

import Bean.Amigo;
import Bean.UsuarioLogueado;
import GUI.Amigo.AgregarAmigo;
import GUI.Canales.DespligueCanalesGUI;
import GUI.TransmitirVideo.TrasmitirVideo;
import Peer2Peer.Point.ClienteP2P;
import Peer2Peer.Point.ServerPeticionesP2P;
import Ruteador.Servidor.ServerPeticionesEnrutamiento;
import de.root1.simon.Simon;
import de.root1.simon.exceptions.NameBindingException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.IOException;
import java.rmi.AccessException;
import java.rmi.AlreadyBoundException;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.Transmitter;
import javax.swing.JButton;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private UsuarioLogueado usuario ;
    private ArrayList<Amigo> usuariosConectados ;
    private ClienteP2P serverPoint ; 
    private ServerPeticionesP2P serverPeticiones;
    public Principal() {
        
        initComponents();
        iniMio();
    }
    public void iniMio(){

            serverPoint = new ClienteP2P(this);
            serverPoint.start();
            serverPeticiones = new ServerPeticionesP2P();
            FormatearBoton(jBChat);
            FormatearBoton(jBAmigos);
            FormatearBoton(jBCanales);
            FormatearBoton(jBCompartirDir);
            FormatearBoton(jBCerrrarSescion1);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBCanales = new javax.swing.JButton();
        jBAmigos = new javax.swing.JButton();
        jBCompartirDir = new javax.swing.JButton();
        jBCerrrarSescion1 = new javax.swing.JButton();
        jBChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jBCanales.setText("Mis canales");
        jBCanales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCanalesActionPerformed(evt);
            }
        });

        jBAmigos.setBackground(new java.awt.Color(198, 198, 167));
        jBAmigos.setFont(new java.awt.Font("Utopia", 1, 18)); // NOI18N
        jBAmigos.setText("Agregar Amigo");
        jBAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAmigosActionPerformed(evt);
            }
        });

        jBCompartirDir.setText("TransmitirVideo");
        jBCompartirDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompartirDirActionPerformed(evt);
            }
        });

        jBCerrrarSescion1.setText("Cerrar Sesión");
        jBCerrrarSescion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrrarSescion1ActionPerformed(evt);
            }
        });

        jBChat.setText("Chat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBCanales, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCompartirDir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBChat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jBCerrrarSescion1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCanales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCompartirDir, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jBCerrrarSescion1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCanalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCanalesActionPerformed
        // TODO add your handling code here:
        DespligueCanalesGUI can = new DespligueCanalesGUI();
        can.setMain(this);
        can.estado(1);
    }//GEN-LAST:event_jBCanalesActionPerformed

    private void jBAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAmigosActionPerformed
        // TODO add your handling code here:
        AgregarAmigo addAmi = new AgregarAmigo(this);
        addAmi.estado(1);
    }//GEN-LAST:event_jBAmigosActionPerformed

    private void jBCompartirDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompartirDirActionPerformed
        // TODO add your handling code here:
        TrasmitirVideo trans = TrasmitirVideo.getInstace(this);
        trans.setVisible(true);
    }//GEN-LAST:event_jBCompartirDirActionPerformed

    private void jBCerrrarSescion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrrarSescion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCerrrarSescion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal p = new Principal();
                p.estado(1);
                p.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAmigos;
    private javax.swing.JButton jBCanales;
    private javax.swing.JButton jBCerrrarSescion1;
    private javax.swing.JButton jBChat;
    private javax.swing.JButton jBCompartirDir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public UsuarioLogueado getUsuario() {
        return usuario;
    }

    public void setUsuario(UsuarioLogueado usuario) {
        this.usuario = usuario;
    }

    public void estado(int a) {
        if (a == 1) {
            this.setVisible(true);
            centrarPantalla();
        }

 }

    public ArrayList<Amigo> getUsuariosConectados() {
        return usuariosConectados;
    }

    public void setUsuariosConectados(ArrayList<Amigo> usuariosConectados) {
        this.usuariosConectados = usuariosConectados;
    }

    public ClienteP2P getServerPoint() {
        return serverPoint;
    }

    public void setServerPoint(ClienteP2P serverPoint) {
        this.serverPoint = serverPoint;
    }

   
    private void centrarPantalla() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((int) (pantalla.width - ventana.width) / 2, (int) (pantalla.height - ventana.height) / 2);

    }

    public ServerPeticionesP2P getServerPeticiones() {
        return serverPeticiones;
    }

    public void setServerPeticiones(ServerPeticionesP2P serverPeticiones) {
        this.serverPeticiones = serverPeticiones;
    }
    public void iniciarServer(){
      
            
             
        try {
            System.out.println("se llama al server y esta ");
            
            
            
            // create the server's registry ...
            de.root1.simon.Registry registry = Simon.createRegistry(22222);
            registry.start();
            // ... where we can bind the serverobject to
            registry.bind("Enrutador", serverPeticiones);
            
            String  nombreServer ="rmi://"+usuario.getAmigoIp()+":"+usuario.getAmigoPuerto()+"/server";
            System.out.println(usuario.getAmigoPuerto());
            System.out.println(nombreServer);
            
            
            System.out.println("se llama al server del cliente y esta corriendo");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NameBindingException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }  
    
    
    
    /***
     * @see formateando botones de la app
     * @param boton 
     */
    private static void FormatearBoton(JButton boton){
        boton.setBackground(Color.white);
        boton.setForeground(Color.black);
        boton.setFont(new Font("utopia",Font.BOLD, 12));
    }
}
