/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NodoLocal;
import GUI.Principal.Principal;
import Bean.AmigoLocal;
import GUI.Principal.login;
import Utilitarios.Encriptacion;
import Utilitarios.Esteticos;
import Utilitarios.Generico;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */

public class InsertarLocal extends javax.swing.JFrame {

    /**
     * Creates new form InsertarLocal
     */
     private login papa; 
     private static InsertarLocal privado = new InsertarLocal();
     public static InsertarLocal getInstance(){
     return privado;
     }
    public InsertarLocal() {
        initComponents();
        setSize(jPanel1.getWidth(), jPanel1.getHeight());
        ImageIcon iconLogo = new ImageIcon("agregarAmigo.png");
        // In init() method write this code
        jLabel6.setIcon(iconLogo);
        setResizable(false);
        Image icono = Toolkit.getDefaultToolkit().getImage("minilogo.png");
        this.setIconImage(icono);
        Esteticos.formatearBoton(jButton1);
        Esteticos.formatearBoton(jButton2);
        Esteticos.formatearTitulo(jLabel5);
        centrarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTNombrePila = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTApodo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtUsuarioLogin = new javax.swing.JTextField();
        jtContra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Usuario");
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jTNombrePila.setText(" ");
        jTNombrePila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombrePilaActionPerformed(evt);
            }
        });

        jLabel2.setText("Apodo:");

        jTApodo.setText(" ");
        jTApodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApodoActionPerformed(evt);
            }
        });

        jLabel3.setText("Usuario:");

        jtUsuarioLogin.setText(" ");
        jtUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Contraseña:");

        jLabel5.setText("INGRESAR USUARIO");

        jButton2.setText("ATRAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtContra)
                            .addComponent(jtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTApodo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombrePila, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTNombrePila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        estado(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioLoginActionPerformed

    private void jTApodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApodoActionPerformed

    private void jTNombrePilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombrePilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombrePilaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String  nombre  =   jTNombrePila.getText();
            String  apodo = jTApodo.getText();
            String login = jtUsuarioLogin.getText();
            String  contra = jtContra.getText();
            String host = InetAddress.getLocalHost().getHostAddress();
            String host1 = getIp();
            String direccionHost = null;
            if (!host.contains("127.0")) {
                direccionHost = host;
            } else if (!host1.equals("0") || !host1.contains("0:0:0")) {
                direccionHost = host1;
            }
            String puerto =  "4545";
            String ruta = "./compartido";
            String estadoActual = "0" ;
            String Certificado = "Amigo:"+nombre+"%%"
            +"AmigoSobreNombre:"+apodo+"%%"
            +"AmigoLogueoName:"+login+"%%"
            + "AmigoIP:"+direccionHost+"%%"
            +"AmigoPuerto:"+puerto+"%%"
            ;
            Certificado = Encriptacion.Encriptar(Certificado);

            AmigoLocal yo = new AmigoLocal();
            yo.setAmigoCertificado("'"+Certificado+"'");
            yo.setAmigoIp("'"+direccionHost+"'");
            yo.setAmigoLogueoName("'"+login+"'");
            yo.setAmigoNombre("'"+nombre+"'");
            yo.setAmigoPassword("'"+contra+"'");
            yo.setAmigoPuerto("'"+puerto+"'");
            yo.setAmigoSobreNombre("'"+apodo+"'");
            yo.setAmigoCertificado("'"+Certificado+"'");
            //            yo.setIdAmigo(Generico.GetNewId("datosnodoactual","IdAmigo"));

            yo.insertar();
        } catch (SQLException | UnknownHostException ex) {
            Logger.getLogger(InsertarLocal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal pi = new Principal();
        pi.estado(1);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTApodo;
    private javax.swing.JTextField jTNombrePila;
    private javax.swing.JPasswordField jtContra;
    private javax.swing.JTextField jtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
 public  void estado (int a ){
 
   if (a==1){
   
   
   this.setVisible(true);
   
   }
  if(a ==2){
            papa.setVisible(true);

            this.setVisible(false);
  }
 }

    private void centrarPantalla() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((int) (pantalla.width - ventana.width) / 2, (int) (pantalla.height - ventana.height) / 2);
    }
    public login getPapa() {
        return papa;
    }

    public void setPapa(login papa) {
        this.papa = papa;
    }

    public void limpiar() {
        jTApodo.setText("");
        jTNombrePila.setText("");
        jtContra.setText("");
        jtUsuarioLogin.setText("");
    }

    public static String getIp() {
        try {
            Enumeration e = NetworkInterface.getNetworkInterfaces();
            int ctr = 0;
            String host = null;
            while (e.hasMoreElements()) {
                NetworkInterface n = (NetworkInterface) e.nextElement();
                Enumeration ee = n.getInetAddresses();
                while (ee.hasMoreElements() && ctr < 3) {
                    ctr++;
                    if (ctr == 3) {
                        break;
                    }
                    InetAddress i = (InetAddress) ee.nextElement();
                    if (ctr == 2) {
                        host = i.getHostAddress();
                    }
                    
                }
            }
            return host;
        } catch (SocketException ex) {
            Logger.getLogger(InsertarLocal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
}
